
# - Only tested with Phred33 quality scores

samples: config/samples.tsv

units: config/units.tsv



#############
### READS ###
#############
reads:
  extension:
    activate: false
    k: 17
    params: "mode=extend ibb=f prefilter=0 el=100 er=100 overwrite=true trimends=9 ecc=t ecco=f conservative=t ignorebadquality"

  derep:
    activate: true
    # vsearch or seqkit
    tool: vsearch
    params: "--strand both --minseqlength 30"

  low_complex:
    params: "maxns=25 minlen=30 entropy=0.6 entropywindow=30 entropyk=6"

report:
  multiqc: "--verbose"
